-- Database schema for FixIt

-- Table for storing user-submitted errors
CREATE TABLE IF NOT EXISTS errors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    error_text TEXT NOT NULL,
    language VARCHAR(50),
    framework VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for storing candidate fixes generated by AI or community
CREATE TABLE IF NOT EXISTS fixes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    error_id UUID REFERENCES errors(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    code_diff TEXT NOT NULL,
    ai_confidence INT DEFAULT 90,
    upvotes INT DEFAULT 0,
    downvotes INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create some index for performance
CREATE INDEX IF NOT EXISTS idx_fixes_error_id ON fixes(error_id);
